spring:
  application:
    name: API Gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: ${AUTH_SERVICE_URI}
            predicates:
              - Path=/api/v1/auth/**
              - Path=/api/v1/user/**
          - id: student-service
            uri: ${STUDENT_SERVICE_URI}
            predicates:
              - Path=/api/students/**

security:
  jwt:
    protected-paths:
      - /api/**
    white-listed-paths:
      - /api/v1/auth/**