spring:
  application:
    name: API Gateway
  http:
    client:
      factory: simple
      read-timeout: 5000
      connect-timeout: 5000

services:
  auth-service: ${AUTH_SERVICE_URI:http://localhost:8081}
  student-service: ${STUDENT_SERVICE_URI:http://localhost:8082}
  course-service: ${COURSE_SERVICE_URI:http://localhost:8083}
  rating-service: ${RATING_SERVICE_URI:http://localhost:8084}
  certification-service: ${CERTIFICATION_SERVICE_URI:http://localhost:8085}
  forum-service: ${FORUM_SERVICE_URI:http://localhost:8086}
  frontend-service: ${FRONTEND_URI:http://localhost:5173}

security:
  jwt:
    protected-paths:
      - /api/**
    white-listed-paths:
      - /api/v1/auth/**
      - /api/v1/users/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
