spring:
  application:
    name: API Gateway
  http:
    client:
      factory: simple
      read-timeout: 5000
      connect-timeout: 5000
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-service
            uri: ${AUTH_SERVICE_URI}
            predicates:
              - Path=/api/v1/users/**,/api/v1/auth/**

          - id: student-service
            uri: ${STUDENT_SERVICE_URI}
            predicates:
              - Path=/api/students/**

          - id: frontend
            uri: ${FRONTEND_URI}
            predicates:
              - Path=/**

security:
  jwt:
    protected-paths:
      - /api/**
    white-listed-paths:
      - /api/v1/auth/**
      - /api/v1/users/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG